######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 20:04:49 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += init.h
SOURCES += init.cpp main.cpp
QT+=network
QT += xml
QT += gui
