#!/bin/bash

Totalxml="/home/axlecho/workplace/github/kx/Total.xml"
Uclxml="/home/axlecho/workplace/github/kx/url.xml"
Infoxml="/home/axlecho/workplace/github/kx/info.xml"

if [ "$1"x == 'inquiry'x ]; then
pushd ./inquiry 1>/dev/null
	./inquiry a | grep $2	
popd 1>/dev/null

elif [ "$1"x == 'init'x ]; then
	pushd ./init 1>/dev/null
		./init
		sed -i 's/gb2312/utf-8/g' ../Total.xml
	popd 1>/dev/null

elif [ "$1"x == 'open'x ];then
	if [ -f  "$Totalxml" ];then
	pushd ./open 1>/dev/null
		./open $2
		sed -i 's/gb2312/utf-8/g' ../url.xml 
	popd 1>/dev/null
	else
		echo "open Totalxml failed."
		exit 0
	fi;

elif [ "$1"x == 'play'x ];then
	if [ -f  "$Uclxml" ]; then  
	pushd ./play 1>/dev/null

		if [ "$#"x == "1"x ];then
			./play "0"
		else 
			./play $2
		fi;

		sed -i 's/gb2312/utf-8/g' ../info.xml 
	popd 1>/dev/null
	else
		echo "open Uclxml failed"
		exit 0
	fi;

	if [ -f "$Infoxml" ]; then  
	pushd ./play2 1>/dev/null
		./play2 | xargs kmplayer
	popd 1>/dev/null
	
	else
		echo "open Infoxml failed"
		exit 0
	fi;
else 
	echo "what the hell going on.."
fi;


