######################################################################
# Automatically generated by qmake (2.01a) Wed Feb 27 20:04:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += play.h
SOURCES += main.cpp play.cpp
QT+=network
QT += xml
QT += gui
