######################################################################
# Automatically generated by qmake (2.01a) Thu Jan 24 08:21:07 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += getter.h ../common/store.h ../common/net.h
SOURCES += get.cpp getter.cpp ../common/store.cpp ../common/net.cpp
QT+=network
QT+=sql
QT += xml
QT += gui
