######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 20:05:21 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += inquiry.h
SOURCES += inquiry.cpp main.cpp
QT+=network
QT+=sql
QT += xml
QT += gui
