######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 20:08:54 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += open.h
SOURCES += main.cpp open.cpp
QT+=network
QT += xml
QT += gui
