######################################################################
# Automatically generated by qmake (2.01a) Tue Feb 26 22:29:32 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += open2.h
SOURCES += main.cpp open2.cpp
QT+=network
QT += xml
QT += gui
